#! /home/fish/prg/fish_main -f

if ($#argv == 0) then
	echo "Usage: $0 dir1 ... dirn"
	exit 1
endif

while ($#argv)
	if (-d $argv[1]) then
		ls -l $argv[1] | cat -n
	else
		echo $0\: No directory $argv[1]
	endif
	shift
end
