#! \home\fish\prg\fish_main.x
set verbose
onintr -
onintr label
goto loop

label0:
	exit 0

loop:
	echo ">loop<"
	source script2
	echo $<
	cat
	echo ok
	goto label2

label:
	echo ">label<"
	echo Interrupted.
	goto loop

label2:
	echo ">label2<"
	goto label0
