__itoa		equ	$00
__itoa0		equ	$01
__htoa		equ	$02
__atoi		equ	$03
__atois		equ	$04
__asc_date	equ	$05
__date1_asc	equ	$06
__date2_asc	equ	$07
__asc_time	equ	$08
__time1_asc	equ	$09
__time2_asc	equ	$0a
__strlen	equ	$0b
__strcpy	equ	$0c
__strncpy	equ	$0d
__strcat	equ	$0e
__strcmp	equ	$0f
__strncmp	equ	$10
__tolower	equ	$11
__toupper	equ	$12
__stolower	equ	$13
__stoupper	equ	$14
__strtokn	equ	$15
__strsrch	equ	$16
__strbsrch	equ	$17
__strbcpy	equ	$18
__msg_keywait	equ	$19
__msg_yes_no	equ	$1a
__print_path	equ	$1b
__print_date1	equ	$1c
__print_date2	equ	$1d
__print_time1	equ	$1e
__print_time2	equ	$1f
__print_prompt	equ	$20
__print_crlf	equ	$21
__print_space	equ	$22
__cprint	equ	$23
__cputchar	equ	$24
__eprint	equ	$25
__name_cut	equ	$26
__fullpath	equ	$27
__srch_name	equ	$28
__wild_conv	equ	$29
__wild_set	equ	$2a
__wild_make_1	equ	$2b
__wild_make_2	equ	$2c
__files		equ	$2d
__drvno_check	equ	$2e
__get_scrsize	equ	$2f
__nextline	equ	$30
__movmem	equ	$31
__skip_numchr	equ	$32
__spcget	equ	$33
__execute	equ	$34
