PW_NAME_SIZE	equ	8
PW_PASSWD_SIZE	equ	13
PW_GECOS_SIZE	equ	98+1+98+1+98+1+98
PW_DIR_SIZE	equ	MAXPATH
PW_SHELL_SIZE	equ	MAXPATH

PW_NAME		equ	0			*  ds.b PW_NAME_SIZE+1
PW_PASSWD	equ	PW_NAME+10		*  ds.b PW_PASSWD_SIZE+1
PW_UID		equ	PW_PASSWD+14		*  ds.w 1
PW_GID		equ	PW_UID+2		*  ds.w 1
PW_GECOS	equ	PW_GID+2		*  ds.b PW_GECOS_SIZE+1
PW_DIR		equ	PW_GECOS+396		*  ds.b PW_DIR_SIZE+1
PW_SHELL	equ	PW_DIR+MAXPATH+2	*  ds.b PW_SHELL_SIZE+1

PW_SIZE		equ	PW_SHELL+MAXPATH+2
