.offset 0
FUNC_SIZE:		ds.l	1
FUNC_PREV:		ds.l	1
FUNC_NEXT:		ds.l	1
FUNC_TYPE:		ds.b	1
FUNC_NAME:		ds.b	MAXFUNCNAMELEN+1
.even
FUNC_HEADER_BOTTOM:

FUNC_HEADER_SIZE	equ	FUNC_HEADER_BOTTOM

FUNCTYPEBIT_SUB		equ	0
FUNCTYPEBIT_SOURCEONCE	equ	1

FUNCTYPEVAL_SUB		equ	1<<FUNCTYPEBIT_SUB
