.offset 0
LOOPINFO_TOPPTR:	ds.l	1
LOOPINFO_TOPLINENO:	ds.l	1
LOOPINFO_BOTPTR:	ds.l	1
LOOPINFO_BOTLINENO:	ds.l	1
LOOPINFO_STORE:		ds.l	1
LOOPINFO_HEADER_BOTTOM:

LOOPINFOSIZE		equ	LOOPINFO_HEADER_BOTTOM
