LOOPINFO_TOPPTR		equ	0
*	ds.l	1
LOOPINFO_TOPLINENO	equ	LOOPINFO_TOPPTR+4
*	ds.l	1
LOOPINFO_BOTPTR		equ	LOOPINFO_TOPLINENO+4
*	ds.l	1
LOOPINFO_BOTLINENO	equ	LOOPINFO_BOTPTR+4
*	ds.l	1
LOOPINFO_STORE		equ	LOOPINFO_BOTLINENO+4
*	ds.l	1
LOOPINFOSIZE		equ	LOOPINFO_STORE+4
