SOURCE_SIZE		equ	0
*	ds.l	1
SOURCE_PARENT		equ	SOURCE_SIZE+4
*	ds.l	1
SOURCE_ONINTR_POINTER	equ	SOURCE_PARENT+4
*	ds.l	1
SOURCE_ONINTR_LINENO	equ	SOURCE_ONINTR_POINTER+4
*	ds.l	1
SOURCE_POINTER		equ	SOURCE_ONINTR_LINENO+4
*	ds.l	1
SOURCE_LINENO		equ	SOURCE_POINTER+4
*	ds.l	1
SOURCE_FILENAME		equ	SOURCE_LINENO+4
*	ds.b	MAXPATH+1
SOURCE_WORDLIST		equ	SOURCE_FILENAME+MAXPATH+1
*	ds.b	MAXWORDLISTSIZE+1
SOURCE_HEADER_SIZE	equ	SOURCE_WORDLIST+MAXWORDLISTSIZE+1	* Åm+1ÇÕóvÇÁÇ»Ç≠Ç∑ÇÈÅn
